### ISSUE TITLE
GitFlow + Semantic Release

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/code-standards#10]
Exploring using [semantic-release-git-branches](https://github.com/bycedric/semantic-release-git-branches) instead of the [`@semantic-release/git`](https://github.com/bycedric/semantic-release-git-branches) plugin.

**Comment by abubakarmani1** [comment]
I have implemented semantic-release-git-branches in bluebaseJS [plugin-console-logger](https://github.com/BlueBaseJS/plugin-console-logger/blob/v1.0.0/.releaserc) and about to open PR for  [code-standards](https://github.com/BlueBaseJS/code-standards/pull/18) so I am closing this issue for now

**Comment by artalat** [comment]
What does this plugin do?

**Comment by artalat** [comment]
cc: @hassans-be
